# Generated by Django 4.2.1 on 2023-05-23 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discord', '0002_topic_room_host_message_room_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-created']},
        ),
    ]
