# Generated by Django 4.2.1 on 2023-06-17 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discord', '0005_room_participants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['updated', '-created']},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['updated', '-created']},
        ),
    ]
